[toolchain]
anchor_version = "0.30.1"

[features]
resolution = false
seeds = false
skip-lint = false

[programs.localnet]
solana = ""
characters = ""

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"  # Or "Mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
